from pydantic import BaseModel


class QueryRequest(BaseModel):
    """Payload for submitting a question to the RAG pipeline."""
    question: str
    session_id: str | None = None
    metadata_filters: dict | None = None
    top_k: int | None = None
    top_k_rerank: int | None = None
    max_per_source: int | None = None
    hybrid_search: bool | None = None


class SourceReference(BaseModel):
    """Metadata about a retrieved chunk used to generate the final answer."""
    file: str
    source_path: str = ""
    document_type: str
    heading: str | None = None
    chunk_preview: str
    score: float


class QueryResponse(BaseModel):
    """The final synchronized answer generated by the LLM, including source references."""
    answer: str
    sources: list[SourceReference]
    session_id: str
    retrieval_scores: list[float]
    model_used: str
    latency_ms: float


class IngestJobResponse(BaseModel):
    """Acknowledges the scheduling of an asynchronous ingestion background job."""
    job_id: str
    status: str


class IngestStatusResponse(BaseModel):
    """Progress report and current state of a running or completed ingestion job."""
    job_id: str
    status: str
    phase: str = "starting"
    documents_processed: int = 0
    documents_total: int = 0
    chunks_created: int = 0
    chunks_updated: int = 0
    chunks_deleted: int = 0
    errors: list[str] = []
    duration_seconds: float = 0.0


class HealthResponse(BaseModel):
    """Service health state, including ChromaDB and LLM provider connectivity."""
    status: str
    chromadb: bool
    llm: bool
    sources_configured: bool = True


class StatsResponse(BaseModel):
    """General statistics about the semantic cache."""
    chunk_count: int


class ProviderInfo(BaseModel):
    """Identifies the current active LLM provider and target model."""
    provider: str
    model: str


class GeminiKeyStatus(BaseModel):
    """Detailed status indicating whether a Gemini key is loaded, and from where (env vs runtime)."""
    has_key: bool
    source: str = "none"


class SidebarState(BaseModel):
    """Aggregated state used by the UI's sidebar to reduce API roundtrips."""
    health: HealthResponse
    provider: ProviderInfo
    gemini_status: GeminiKeyStatus
    available_categories: list[str]


class SwitchProviderRequest(BaseModel):
    """Payload for changing the active LLM provider at runtime."""
    provider: str  # "ollama" | "gemini"
